from __future__ import annotations

import asyncio

from sqlalchemy import select

from app.db.session import get_sessionmaker
from app.models.geo import Pays


PAYS_DATA = [
    ("AF", "Afghanistan", "Asie"),
    ("ZA", "Afrique du Sud", "Afrique"),
    ("AL", "Albanie", "Europe"),
    ("DZ", "Algérie", "Afrique"),
    ("DE", "Allemagne", "Europe"),
    ("AD", "Andorre", "Europe"),
    ("AO", "Angola", "Afrique"),
    ("AG", "Antigua-et-Barbuda", "Amérique"),
    ("SA", "Arabie Saoudite", "Asie"),
    ("AR", "Argentine", "Amérique"),
    ("AM", "Arménie", "Asie"),
    ("AU", "Australie", "Océanie"),
    ("AT", "Autriche", "Europe"),
    ("AZ", "Azerbaïdjan", "Asie"),
    ("BS", "Bahamas", "Amérique"),
    ("BH", "Bahreïn", "Asie"),
    ("BD", "Bangladesh", "Asie"),
    ("BB", "Barbade", "Amérique"),
    ("BY", "Biélorussie", "Europe"),
    ("BE", "Belgique", "Europe"),
    ("BZ", "Belize", "Amérique"),
    ("BJ", "Bénin", "Afrique"),
    ("BT", "Bhoutan", "Asie"),
    ("BO", "Bolivie", "Amérique"),
    ("BA", "Bosnie-Herzégovine", "Europe"),
    ("BW", "Botswana", "Afrique"),
    ("BR", "Brésil", "Amérique"),
    ("BN", "Brunei", "Asie"),
    ("BG", "Bulgarie", "Europe"),
    ("BF", "Burkina Faso", "Afrique"),
    ("BI", "Burundi", "Afrique"),
    ("CV", "Cabo Verde", "Afrique"),
    ("KH", "Cambodge", "Asie"),
    ("CM", "Cameroun", "Afrique"),
    ("CA", "Canada", "Amérique"),
    ("CF", "République centrafricaine", "Afrique"),
    ("CL", "Chili", "Amérique"),
    ("CN", "Chine", "Asie"),
    ("CY", "Chypre", "Asie"),
    ("CO", "Colombie", "Amérique"),
    ("KM", "Comores", "Afrique"),
    ("CG", "Congo", "Afrique"),
    ("CD", "République démocratique du Congo", "Afrique"),
    ("CR", "Costa Rica", "Amérique"),
    ("CI", "Côte d'Ivoire", "Afrique"),
    ("HR", "Croatie", "Europe"),
    ("CU", "Cuba", "Amérique"),
    ("DK", "Danemark", "Europe"),
    ("DJ", "Djibouti", "Afrique"),
    ("DO", "République dominicaine", "Amérique"),
    ("EG", "Égypte", "Afrique"),
    ("AE", "Émirats arabes unis", "Asie"),
    ("EC", "Équateur", "Amérique"),
    ("ER", "Érythrée", "Afrique"),
    ("ES", "Espagne", "Europe"),
    ("EE", "Estonie", "Europe"),
    ("SZ", "Eswatini", "Afrique"),
    ("ET", "Éthiopie", "Afrique"),
    ("FJ", "Fidji", "Océanie"),
    ("FI", "Finlande", "Europe"),
    ("FR", "France", "Europe"),
    ("GA", "Gabon", "Afrique"),
    ("GM", "Gambie", "Afrique"),
    ("GE", "Géorgie", "Asie"),
    ("GH", "Ghana", "Afrique"),
    ("GR", "Grèce", "Europe"),
    ("GD", "Grenade", "Amérique"),
    ("GT", "Guatemala", "Amérique"),
    ("GN", "Guinée", "Afrique"),
    ("GW", "Guinée-Bissau", "Afrique"),
    ("GQ", "Guinée équatoriale", "Afrique"),
    ("GY", "Guyana", "Amérique"),
    ("HT", "Haïti", "Amérique"),
    ("HN", "Honduras", "Amérique"),
    ("HU", "Hongrie", "Europe"),
    ("IN", "Inde", "Asie"),
    ("ID", "Indonésie", "Asie"),
    ("IQ", "Irak", "Asie"),
    ("IR", "Iran", "Asie"),
    ("IE", "Irlande", "Europe"),
    ("IS", "Islande", "Europe"),
    ("IL", "Israël", "Asie"),
    ("IT", "Italie", "Europe"),
    ("JM", "Jamaïque", "Amérique"),
    ("JP", "Japon", "Asie"),
    ("JO", "Jordanie", "Asie"),
    ("KZ", "Kazakhstan", "Asie"),
    ("KE", "Kenya", "Afrique"),
    ("KG", "Kirghizistan", "Asie"),
    ("KI", "Kiribati", "Océanie"),
    ("KW", "Koweït", "Asie"),
    ("LA", "Laos", "Asie"),
    ("LS", "Lesotho", "Afrique"),
    ("LV", "Lettonie", "Europe"),
    ("LB", "Liban", "Asie"),
    ("LR", "Liberia", "Afrique"),
    ("LY", "Libye", "Afrique"),
    ("LI", "Liechtenstein", "Europe"),
    ("LT", "Lituanie", "Europe"),
    ("LU", "Luxembourg", "Europe"),
    ("MK", "Macédoine du Nord", "Europe"),
    ("MG", "Madagascar", "Afrique"),
    ("MY", "Malaisie", "Asie"),
    ("MW", "Malawi", "Afrique"),
    ("MV", "Maldives", "Asie"),
    ("ML", "Mali", "Afrique"),
    ("MT", "Malte", "Europe"),
    ("MA", "Maroc", "Afrique"),
    ("MH", "Îles Marshall", "Océanie"),
    ("MU", "Maurice", "Afrique"),
    ("MR", "Mauritanie", "Afrique"),
    ("MX", "Mexique", "Amérique"),
    ("FM", "Micronésie", "Océanie"),
    ("MD", "Moldavie", "Europe"),
    ("MC", "Monaco", "Europe"),
    ("MN", "Mongolie", "Asie"),
    ("ME", "Monténégro", "Europe"),
    ("MZ", "Mozambique", "Afrique"),
    ("MM", "Myanmar", "Asie"),
    ("NA", "Namibie", "Afrique"),
    ("NR", "Nauru", "Océanie"),
    ("NP", "Népal", "Asie"),
    ("NI", "Nicaragua", "Amérique"),
    ("NE", "Niger", "Afrique"),
    ("NG", "Nigeria", "Afrique"),
    ("NO", "Norvège", "Europe"),
    ("NZ", "Nouvelle-Zélande", "Océanie"),
    ("OM", "Oman", "Asie"),
    ("UG", "Ouganda", "Afrique"),
    ("UZ", "Ouzbékistan", "Asie"),
    ("PK", "Pakistan", "Asie"),
    ("PW", "Palaos", "Océanie"),
    ("PA", "Panama", "Amérique"),
    ("PG", "Papouasie-Nouvelle-Guinée", "Océanie"),
    ("PY", "Paraguay", "Amérique"),
    ("NL", "Pays-Bas", "Europe"),
    ("PE", "Pérou", "Amérique"),
    ("PH", "Philippines", "Asie"),
    ("PL", "Pologne", "Europe"),
    ("PT", "Portugal", "Europe"),
    ("QA", "Qatar", "Asie"),
    ("RO", "Roumanie", "Europe"),
    ("GB", "Royaume-Uni", "Europe"),
    ("RU", "Russie", "Europe"),
    ("RW", "Rwanda", "Afrique"),
    ("KN", "Saint-Kitts-et-Nevis", "Amérique"),
    ("LC", "Sainte-Lucie", "Amérique"),
    ("VC", "Saint-Vincent-et-les Grenadines", "Amérique"),
    ("SB", "Îles Salomon", "Océanie"),
    ("WS", "Samoa", "Océanie"),
    ("SM", "Saint-Marin", "Europe"),
    ("ST", "Sao Tomé-et-Principe", "Afrique"),
    ("SN", "Sénégal", "Afrique"),
    ("RS", "Serbie", "Europe"),
    ("SC", "Seychelles", "Afrique"),
    ("SL", "Sierra Leone", "Afrique"),
    ("SG", "Singapour", "Asie"),
    ("SK", "Slovaquie", "Europe"),
    ("SI", "Slovénie", "Europe"),
    ("SO", "Somalie", "Afrique"),
    ("SD", "Soudan", "Afrique"),
    ("SS", "Soudan du Sud", "Afrique"),
    ("LK", "Sri Lanka", "Asie"),
    ("SE", "Suède", "Europe"),
    ("CH", "Suisse", "Europe"),
    ("SR", "Suriname", "Amérique"),
    ("SY", "Syrie", "Asie"),
    ("TJ", "Tadjikistan", "Asie"),
    ("TZ", "Tanzanie", "Afrique"),
    ("TD", "Tchad", "Afrique"),
    ("CZ", "Tchéquie", "Europe"),
    ("TH", "Thaïlande", "Asie"),
    ("TL", "Timor oriental", "Asie"),
    ("TG", "Togo", "Afrique"),
    ("TO", "Tonga", "Océanie"),
    ("TT", "Trinité-et-Tobago", "Amérique"),
    ("TN", "Tunisie", "Afrique"),
    ("TM", "Turkménistan", "Asie"),
    ("TR", "Turquie", "Asie"),
    ("TV", "Tuvalu", "Océanie"),
    ("UA", "Ukraine", "Europe"),
    ("UY", "Uruguay", "Amérique"),
    ("VU", "Vanuatu", "Océanie"),
    ("VE", "Venezuela", "Amérique"),
    ("VN", "Vietnam", "Asie"),
    ("YE", "Yémen", "Asie"),
    ("ZM", "Zambie", "Afrique"),
    ("ZW", "Zimbabwe", "Afrique"),
    ("US", "États-Unis", "Amérique"),
]


async def seed_pays() -> None:
    async with get_sessionmaker()() as session:
        existing = await session.execute(select(Pays.code))
        existing_codes = {row[0] for row in existing.all()}

        inserted = 0
        for code, nom, continent in PAYS_DATA:
            if code not in existing_codes:
                session.add(Pays(code=code, nom=nom, continent=continent))
                inserted += 1

        await session.commit()
        print(f"{inserted} pays insérés.")


if __name__ == "__main__":
    asyncio.run(seed_pays())
