"""Add dual validation fields to adhesion

Revision ID: 3317fc3810d3
Revises: 0002_photo_recto_verso
Create Date: 2026-07-29 15:23:18.156320

"""

from alembic import op
import sqlalchemy as sa
from app.db import types



revision = '3317fc3810d3'
down_revision = '0002_photo_recto_verso'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adhesions', sa.Column('validation_accueil_user_id', types.GUID(length=36), nullable=True))
    op.add_column('adhesions', sa.Column('validation_accueil_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('adhesions', sa.Column('validation_directoire_user_id', types.GUID(length=36), nullable=True))
    op.add_column('adhesions', sa.Column('validation_directoire_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('adhesions', 'statut',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('en_attente', 'validee_accueil', 'validee', 'rejetee', 'complement', name='adhesion_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'en_attente'::character varying"))
    op.drop_index(op.f('uq_adhesions_idempotency_key'), table_name='adhesions')
    op.create_index(op.f('ix_adhesions_commune_domicile_id'), 'adhesions', ['commune_domicile_id'], unique=False)
    op.create_index(op.f('ix_adhesions_departement_domicile_id'), 'adhesions', ['departement_domicile_id'], unique=False)
    op.create_index(op.f('ix_adhesions_departement_militantisme_id'), 'adhesions', ['departement_militantisme_id'], unique=False)
    op.create_index(op.f('ix_adhesions_region_domicile_id'), 'adhesions', ['region_domicile_id'], unique=False)
    op.create_index(op.f('ix_adhesions_region_militantisme_id'), 'adhesions', ['region_militantisme_id'], unique=False)
    op.create_unique_constraint(None, 'adhesions', ['idempotency_key'])
    op.create_foreign_key(None, 'adhesions', 'users', ['validation_directoire_user_id'], ['id'])
    op.create_foreign_key(None, 'adhesions', 'users', ['validation_accueil_user_id'], ['id'])
    op.alter_column('user_roles', 'role',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('admin', 'comite_accueil', 'comite_directoire', 'user', name='app_role', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'role',
               existing_type=sa.Enum('admin', 'comite_accueil', 'comite_directoire', 'user', name='app_role', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.drop_constraint(None, 'adhesions', type_='foreignkey')
    op.drop_constraint(None, 'adhesions', type_='foreignkey')
    op.drop_constraint(None, 'adhesions', type_='unique')
    op.drop_index(op.f('ix_adhesions_region_militantisme_id'), table_name='adhesions')
    op.drop_index(op.f('ix_adhesions_region_domicile_id'), table_name='adhesions')
    op.drop_index(op.f('ix_adhesions_departement_militantisme_id'), table_name='adhesions')
    op.drop_index(op.f('ix_adhesions_departement_domicile_id'), table_name='adhesions')
    op.drop_index(op.f('ix_adhesions_commune_domicile_id'), table_name='adhesions')
    op.create_index(op.f('uq_adhesions_idempotency_key'), 'adhesions', ['idempotency_key'], unique=True)
    op.alter_column('adhesions', 'statut',
               existing_type=sa.Enum('en_attente', 'validee_accueil', 'validee', 'rejetee', 'complement', name='adhesion_status', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'en_attente'::character varying"))
    op.drop_column('adhesions', 'validation_directoire_at')
    op.drop_column('adhesions', 'validation_directoire_user_id')
    op.drop_column('adhesions', 'validation_accueil_at')
    op.drop_column('adhesions', 'validation_accueil_user_id')
    # ### end Alembic commands ###

